spring:
  application:
    name: payment-service
  config:
    import: 'optional:configserver:${config-server:http://192.168.1.15:9090/}'
  profiles:
    active: '${active-profile:dev}'
  cloud:
    config:
      uri: '${config-server:http://192.168.1.15:9090/}'
      name: app-server,payment-service
